### ISSUE TITLE
Issue avec toflit18_data UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position

### ISSUE THREAD

**Issue by gdaudin** [medialab/toflit18#206]
Lorsque je lance les deux scripts pythons suivant dos à dos:

aggregate_sources_in_bdd_centrale.py
et
split_bdd_centrale_in_sources.py  

j’ai l’erreur:

`guillaumedaudin@Oronte scripts % python3 /Users/guillaumedaudin/Documents/Recherche/Commerce\ International\ Français\ XVIIIe.xls/Balance\ du\ commerce/Retranscriptions_Commerce_France/toflit18_data_GIT/scripts/split_bdd_centrale_in_sources.py
Traceback (most recent call last):
  File "/Users/guillaumedaudin/Documents/Recherche/Commerce International Français XVIIIe.xls/Balance du commerce/Retranscriptions_Commerce_France/toflit18_data_GIT/scripts/split_bdd_centrale_in_sources.py", line 59, in <module>
    existing_files[filepath] = sum((1 for _ in f)) - 1
  File "/Users/guillaumedaudin/Documents/Recherche/Commerce International Français XVIIIe.xls/Balance du commerce/Retranscriptions_Commerce_France/toflit18_data_GIT/scripts/split_bdd_centrale_in_sources.py", line 59, in <genexpr>
    existing_files[filepath] = sum((1 for _ in f)) - 1
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 3131: invalid start byte`

**Comment by gdaudin** [comment]
Pas au bon endroit
