### ISSUE TITLE
Le script "split_bdd_centrale_in_sources.py" (dans Toflit18_data) ne fonctionne pas

### ISSUE THREAD

**Issue by gdaudin** [medialab/toflit18#233]
Voici l’erreur : 

(base) guillaumedaudin@Oronte-2 scripts % python3 /Users/guillaumedaudin/Répertoires\ Git/toflit18_data_GIT/scripts/split_bdd_centrale_in_sources.py 
Traceback (most recent call last):
  File "/Users/guillaumedaudin/Répertoires Git/toflit18_data_GIT/scripts/split_bdd_centrale_in_sources.py", line 62, in <module>
    existing_files[filepath] = sum((1 for _ in blouf))
  File "/Users/guillaumedaudin/Répertoires Git/toflit18_data_GIT/scripts/split_bdd_centrale_in_sources.py", line 62, in <genexpr>
    existing_files[filepath] = sum((1 for _ in blouf))
  File "/Users/guillaumedaudin/opt/anaconda3/lib/python3.8/csv.py", line 110, in __next__
    self.fieldnames
  File "/Users/guillaumedaudin/opt/anaconda3/lib/python3.8/csv.py", line 97, in fieldnames
    self._fieldnames = next(self.reader)
  File "/Users/guillaumedaudin/opt/anaconda3/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 3131: invalid start byte
(base) guillaumedaudin@Oronte-2 scripts %

**Comment by gdaudin** [comment]
Réglé en local par Paul
